version: "3.8"
services:
  algoforce-app:
    build: .
    container_name: algoforce-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - algoforce-db
      - redis

  algoforce-db:
    image: postgres:15
    container_name: algoforce-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8888:8080"
