services:
  algoforce-db:
    image: postgres:latest
    container_name: algoforce-db
    restart: always
    environment:
      POSTGRES_DB: algoforce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!
    ports:
      - "5432:5432"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
