Clist:
  api_key:
    b101e1395be8a558b88945f783760f124c520738
  username:
    v4vinamra

SECRET:
    key:
      TaK+HaV^uvCHEFsEVfypW#7g9^k*Z8$V

spring:
  data:
    redis:
      host: localhost
      port: 6379